### ISSUE TITLE
Custom Background color

### ISSUE THREAD

**Issue by pacmanincarnate** [Eradev/backyardai-styles#2]
I bet some people would love a custom background color. Some people aren't into having an image back there. Not sure what control you might have over font, but that would also be really cool.

This is a great project. I know a number of people would who would love it

**Comment by Eradev** [comment]
Background color is done.

The thing with fonts is that you need to load it and well as set the value to use it. I could load a few Google fonts and put a dropdown but I'd need to know which one people want.

**Comment by Eradev** [comment]
Closed for lack of feedback. Reopen it or create a new one if it's still relevant.
